name:first work flow:

on:
  push:
    bransh:
      -main

jobs:
  example-job:
    runs-on: ubuntu-latest

  
    steps:
      -name: print a welcome message
       run: echo "welcome Ahmed"
       
